name: Pytest Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage-report:
    strategy:
      matrix:
        python-version:
          - 3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build dependencies
        run: pip install --upgrade setuptools
      - name: Install dot env
        run: pip install python-dotenv
      - name: Install requests
        run: pip install requests
      - name: Change to test directory
        run: cd tests/unit
      - uses: lpenz/ghaction-pytest-cov@v1
      - uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
       
          
  coverage-finish:
    needs: coverage-report
    runs-on: ubuntu-latest
    steps:
      - uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel-finished: true